### ISSUE TITLE
If bot is restarted starboard may be repeated & missed reactions

### ISSUE THREAD

**Issue by Coca162** [TudbuT/oxibot#13]
Since we do not hold tracked messages in persistent storage if the bot gets restarted there is potential for people to re-react and cause duplicate posts. This can be solved by moving starboard_tracked from `Data` into its own sql table.

If people react to a message when a bot is shut down and then remove their reaction the post reduces the reaction count when it shouldn't. This can be stopped by keeping an array of the individuals who reacted to a message in postgres but I feel as though this edge case shouldn't be fixed due to the size increase for the (mostly unnecessary) extra reliability

**Comment by abrasmag3** [comment]
This will also help implement many features suggested in #5
